# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: worker/pb/observe.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'worker/pb/observe.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17worker/pb/observe.proto\x12\tworker.pb\"$\n\x0eObserveRequest\x12\x12\n\nhypothesis\x18\x01 \x01(\t\"P\n\x0fObserveResponse\x12\x12\n\nhypothesis\x18\x01 \x01(\t\x12\x14\n\x0cquantitative\x18\x02 \x01(\x01\x12\x13\n\x0bqualitative\x18\x03 \x01(\t2M\n\x07Observe\x12\x42\n\x07observe\x12\x19.worker.pb.ObserveRequest\x1a\x1a.worker.pb.ObserveResponse\"\x00\x42\x1dZ\x1borchestrator/internal/pb;pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'worker.pb.observe_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\033orchestrator/internal/pb;pb'
  _globals['_OBSERVEREQUEST']._serialized_start=38
  _globals['_OBSERVEREQUEST']._serialized_end=74
  _globals['_OBSERVERESPONSE']._serialized_start=76
  _globals['_OBSERVERESPONSE']._serialized_end=156
  _globals['_OBSERVE']._serialized_start=158
  _globals['_OBSERVE']._serialized_end=235
# @@protoc_insertion_point(module_scope)
