# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: worker/pb/propose.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'worker/pb/propose.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17worker/pb/propose.proto\x12\tworker.pb\x1a\x1cgoogle/protobuf/struct.proto\"J\n\tCandidate\x12\x12\n\nhypothesis\x18\x01 \x01(\t\x12\x14\n\x0cquantitative\x18\x02 \x01(\x01\x12\x13\n\x0bqualitative\x18\x03 \x01(\t\"g\n\x0eProposeRequest\x12%\n\x07parents\x18\x01 \x03(\x0b\x32\x14.worker.pb.Candidate\x12.\n\rspecification\x18\x02 \x01(\x0b\x32\x17.google.protobuf.Struct\"\'\n\x0fProposeResponse\x12\x14\n\x0chypothesises\x18\x01 \x03(\t2M\n\x07Propose\x12\x42\n\x07propose\x12\x19.worker.pb.ProposeRequest\x1a\x1a.worker.pb.ProposeResponse\"\x00\x42\x1dZ\x1borchestrator/internal/pb;pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'worker.pb.propose_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\033orchestrator/internal/pb;pb'
  _globals['_CANDIDATE']._serialized_start=68
  _globals['_CANDIDATE']._serialized_end=142
  _globals['_PROPOSEREQUEST']._serialized_start=144
  _globals['_PROPOSEREQUEST']._serialized_end=247
  _globals['_PROPOSERESPONSE']._serialized_start=249
  _globals['_PROPOSERESPONSE']._serialized_end=288
  _globals['_PROPOSE']._serialized_start=290
  _globals['_PROPOSE']._serialized_end=367
# @@protoc_insertion_point(module_scope)
