# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: worker/pb/worker.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'worker/pb/worker.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16worker/pb/worker.proto\x12\tworker.pb\"J\n\tCandidate\x12\x12\n\nhypothesis\x18\x01 \x01(\t\x12\x14\n\x0cquantitative\x18\x02 \x01(\x01\x12\x13\n\x0bqualitative\x18\x03 \x01(\t\"N\n\x0eProposeRequest\x12%\n\x07parents\x18\x01 \x03(\x0b\x32\x14.worker.pb.Candidate\x12\x15\n\rspecification\x18\x02 \x01(\t\"\'\n\x0fProposeResponse\x12\x14\n\x0chypothesises\x18\x01 \x03(\t\"$\n\x0eObserveRequest\x12\x12\n\nhypothesis\x18\x01 \x01(\t\"P\n\x0fObserveResponse\x12\x12\n\nhypothesis\x18\x01 \x01(\t\x12\x14\n\x0cquantitative\x18\x02 \x01(\x01\x12\x13\n\x0bqualitative\x18\x03 \x01(\t2\x90\x01\n\x06WORKER\x12\x42\n\x07propose\x12\x19.worker.pb.ProposeRequest\x1a\x1a.worker.pb.ProposeResponse\"\x00\x12\x42\n\x07observe\x12\x19.worker.pb.ObserveRequest\x1a\x1a.worker.pb.ObserveResponse\"\x00\x42\x1dZ\x1borchestrator/internal/pb;pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'worker.pb.worker_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\033orchestrator/internal/pb;pb'
  _globals['_CANDIDATE']._serialized_start=37
  _globals['_CANDIDATE']._serialized_end=111
  _globals['_PROPOSEREQUEST']._serialized_start=113
  _globals['_PROPOSEREQUEST']._serialized_end=191
  _globals['_PROPOSERESPONSE']._serialized_start=193
  _globals['_PROPOSERESPONSE']._serialized_end=232
  _globals['_OBSERVEREQUEST']._serialized_start=234
  _globals['_OBSERVEREQUEST']._serialized_end=270
  _globals['_OBSERVERESPONSE']._serialized_start=272
  _globals['_OBSERVERESPONSE']._serialized_end=352
  _globals['_WORKER']._serialized_start=355
  _globals['_WORKER']._serialized_end=499
# @@protoc_insertion_point(module_scope)
