// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v6.32.1
// source: pb/llmsr.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// LLMSRClient is the client API for LLMSR service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LLMSRClient interface {
	// Propose generates new program skeletons based on parent programs.
	Propose(ctx context.Context, in *ProposeRequest, opts ...grpc.CallOption) (*ProposeResponse, error)
	// Observe evaluates a given program skeleton and returns its performance score.
	Observe(ctx context.Context, in *ObserveRequest, opts ...grpc.CallOption) (*ObserveResponse, error)
}

type lLMSRClient struct {
	cc grpc.ClientConnInterface
}

func NewLLMSRClient(cc grpc.ClientConnInterface) LLMSRClient {
	return &lLMSRClient{cc}
}

func (c *lLMSRClient) Propose(ctx context.Context, in *ProposeRequest, opts ...grpc.CallOption) (*ProposeResponse, error) {
	out := new(ProposeResponse)
	err := c.cc.Invoke(ctx, "/llmsr_worker.pb.LLMSR/Propose", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lLMSRClient) Observe(ctx context.Context, in *ObserveRequest, opts ...grpc.CallOption) (*ObserveResponse, error) {
	out := new(ObserveResponse)
	err := c.cc.Invoke(ctx, "/llmsr_worker.pb.LLMSR/Observe", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LLMSRServer is the server API for LLMSR service.
// All implementations must embed UnimplementedLLMSRServer
// for forward compatibility
type LLMSRServer interface {
	// Propose generates new program skeletons based on parent programs.
	Propose(context.Context, *ProposeRequest) (*ProposeResponse, error)
	// Observe evaluates a given program skeleton and returns its performance score.
	Observe(context.Context, *ObserveRequest) (*ObserveResponse, error)
	mustEmbedUnimplementedLLMSRServer()
}

// UnimplementedLLMSRServer must be embedded to have forward compatible implementations.
type UnimplementedLLMSRServer struct {
}

func (UnimplementedLLMSRServer) Propose(context.Context, *ProposeRequest) (*ProposeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Propose not implemented")
}
func (UnimplementedLLMSRServer) Observe(context.Context, *ObserveRequest) (*ObserveResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Observe not implemented")
}
func (UnimplementedLLMSRServer) mustEmbedUnimplementedLLMSRServer() {}

// UnsafeLLMSRServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LLMSRServer will
// result in compilation errors.
type UnsafeLLMSRServer interface {
	mustEmbedUnimplementedLLMSRServer()
}

func RegisterLLMSRServer(s grpc.ServiceRegistrar, srv LLMSRServer) {
	s.RegisterService(&LLMSR_ServiceDesc, srv)
}

func _LLMSR_Propose_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProposeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LLMSRServer).Propose(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/llmsr_worker.pb.LLMSR/Propose",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LLMSRServer).Propose(ctx, req.(*ProposeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LLMSR_Observe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ObserveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LLMSRServer).Observe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/llmsr_worker.pb.LLMSR/Observe",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LLMSRServer).Observe(ctx, req.(*ObserveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LLMSR_ServiceDesc is the grpc.ServiceDesc for LLMSR service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LLMSR_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "llmsr_worker.pb.LLMSR",
	HandlerType: (*LLMSRServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Propose",
			Handler:    _LLMSR_Propose_Handler,
		},
		{
			MethodName: "Observe",
			Handler:    _LLMSR_Observe_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/llmsr.proto",
}
