// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: pb/observe.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Observe_Observe_FullMethodName = "/worker.pb.Observe/observe"
)

// ObserveClient is the client API for Observe service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Observe service evaluates a given candidate hypothesis and returns its performance quantitative.
type ObserveClient interface {
	Observe(ctx context.Context, in *ObserveRequest, opts ...grpc.CallOption) (*ObserveResponse, error)
}

type observeClient struct {
	cc grpc.ClientConnInterface
}

func NewObserveClient(cc grpc.ClientConnInterface) ObserveClient {
	return &observeClient{cc}
}

func (c *observeClient) Observe(ctx context.Context, in *ObserveRequest, opts ...grpc.CallOption) (*ObserveResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ObserveResponse)
	err := c.cc.Invoke(ctx, Observe_Observe_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ObserveServer is the server API for Observe service.
// All implementations must embed UnimplementedObserveServer
// for forward compatibility.
//
// Observe service evaluates a given candidate hypothesis and returns its performance quantitative.
type ObserveServer interface {
	Observe(context.Context, *ObserveRequest) (*ObserveResponse, error)
	mustEmbedUnimplementedObserveServer()
}

// UnimplementedObserveServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedObserveServer struct{}

func (UnimplementedObserveServer) Observe(context.Context, *ObserveRequest) (*ObserveResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Observe not implemented")
}
func (UnimplementedObserveServer) mustEmbedUnimplementedObserveServer() {}
func (UnimplementedObserveServer) testEmbeddedByValue()                 {}

// UnsafeObserveServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ObserveServer will
// result in compilation errors.
type UnsafeObserveServer interface {
	mustEmbedUnimplementedObserveServer()
}

func RegisterObserveServer(s grpc.ServiceRegistrar, srv ObserveServer) {
	// If the following call panics, it indicates UnimplementedObserveServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Observe_ServiceDesc, srv)
}

func _Observe_Observe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ObserveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ObserveServer).Observe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Observe_Observe_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ObserveServer).Observe(ctx, req.(*ObserveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Observe_ServiceDesc is the grpc.ServiceDesc for Observe service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Observe_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "worker.pb.Observe",
	HandlerType: (*ObserveServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "observe",
			Handler:    _Observe_Observe_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/observe.proto",
}
