// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: pb/propose.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Propose_Propose_FullMethodName = "/worker.pb.Propose/propose"
)

// ProposeClient is the client API for Propose service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Propose service generates new candidate hypothesises based on parent candidates.
type ProposeClient interface {
	Propose(ctx context.Context, in *ProposeRequest, opts ...grpc.CallOption) (*ProposeResponse, error)
}

type proposeClient struct {
	cc grpc.ClientConnInterface
}

func NewProposeClient(cc grpc.ClientConnInterface) ProposeClient {
	return &proposeClient{cc}
}

func (c *proposeClient) Propose(ctx context.Context, in *ProposeRequest, opts ...grpc.CallOption) (*ProposeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProposeResponse)
	err := c.cc.Invoke(ctx, Propose_Propose_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProposeServer is the server API for Propose service.
// All implementations must embed UnimplementedProposeServer
// for forward compatibility.
//
// Propose service generates new candidate hypothesises based on parent candidates.
type ProposeServer interface {
	Propose(context.Context, *ProposeRequest) (*ProposeResponse, error)
	mustEmbedUnimplementedProposeServer()
}

// UnimplementedProposeServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProposeServer struct{}

func (UnimplementedProposeServer) Propose(context.Context, *ProposeRequest) (*ProposeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Propose not implemented")
}
func (UnimplementedProposeServer) mustEmbedUnimplementedProposeServer() {}
func (UnimplementedProposeServer) testEmbeddedByValue()                 {}

// UnsafeProposeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProposeServer will
// result in compilation errors.
type UnsafeProposeServer interface {
	mustEmbedUnimplementedProposeServer()
}

func RegisterProposeServer(s grpc.ServiceRegistrar, srv ProposeServer) {
	// If the following call panics, it indicates UnimplementedProposeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Propose_ServiceDesc, srv)
}

func _Propose_Propose_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProposeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProposeServer).Propose(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Propose_Propose_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProposeServer).Propose(ctx, req.(*ProposeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Propose_ServiceDesc is the grpc.ServiceDesc for Propose service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Propose_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "worker.pb.Propose",
	HandlerType: (*ProposeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "propose",
			Handler:    _Propose_Propose_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/propose.proto",
}
