// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.0
// source: pb/worker.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WORKER_Propose_FullMethodName = "/worker.pb.WORKER/propose"
	WORKER_Observe_FullMethodName = "/worker.pb.WORKER/observe"
)

// WORKERClient is the client API for WORKER service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// worker service definition.
type WORKERClient interface {
	// propose generates new candidate hypothesises based on parent candidates.
	Propose(ctx context.Context, in *ProposeRequest, opts ...grpc.CallOption) (*ProposeResponse, error)
	// observe evaluates a given candidate hypothesis and returns its performance quantitative.
	Observe(ctx context.Context, in *ObserveRequest, opts ...grpc.CallOption) (*ObserveResponse, error)
}

type wORKERClient struct {
	cc grpc.ClientConnInterface
}

func NewWORKERClient(cc grpc.ClientConnInterface) WORKERClient {
	return &wORKERClient{cc}
}

func (c *wORKERClient) Propose(ctx context.Context, in *ProposeRequest, opts ...grpc.CallOption) (*ProposeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProposeResponse)
	err := c.cc.Invoke(ctx, WORKER_Propose_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wORKERClient) Observe(ctx context.Context, in *ObserveRequest, opts ...grpc.CallOption) (*ObserveResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ObserveResponse)
	err := c.cc.Invoke(ctx, WORKER_Observe_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WORKERServer is the server API for WORKER service.
// All implementations must embed UnimplementedWORKERServer
// for forward compatibility.
//
// worker service definition.
type WORKERServer interface {
	// propose generates new candidate hypothesises based on parent candidates.
	Propose(context.Context, *ProposeRequest) (*ProposeResponse, error)
	// observe evaluates a given candidate hypothesis and returns its performance quantitative.
	Observe(context.Context, *ObserveRequest) (*ObserveResponse, error)
	mustEmbedUnimplementedWORKERServer()
}

// UnimplementedWORKERServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWORKERServer struct{}

func (UnimplementedWORKERServer) Propose(context.Context, *ProposeRequest) (*ProposeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Propose not implemented")
}
func (UnimplementedWORKERServer) Observe(context.Context, *ObserveRequest) (*ObserveResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Observe not implemented")
}
func (UnimplementedWORKERServer) mustEmbedUnimplementedWORKERServer() {}
func (UnimplementedWORKERServer) testEmbeddedByValue()                {}

// UnsafeWORKERServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WORKERServer will
// result in compilation errors.
type UnsafeWORKERServer interface {
	mustEmbedUnimplementedWORKERServer()
}

func RegisterWORKERServer(s grpc.ServiceRegistrar, srv WORKERServer) {
	// If the following call pancis, it indicates UnimplementedWORKERServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WORKER_ServiceDesc, srv)
}

func _WORKER_Propose_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProposeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WORKERServer).Propose(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WORKER_Propose_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WORKERServer).Propose(ctx, req.(*ProposeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WORKER_Observe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ObserveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WORKERServer).Observe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WORKER_Observe_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WORKERServer).Observe(ctx, req.(*ObserveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WORKER_ServiceDesc is the grpc.ServiceDesc for WORKER service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WORKER_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "worker.pb.WORKER",
	HandlerType: (*WORKERServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "propose",
			Handler:    _WORKER_Propose_Handler,
		},
		{
			MethodName: "observe",
			Handler:    _WORKER_Observe_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/worker.proto",
}
